const POSTGRES_SCHEMA_VERSION = 6;

const POSTGRES_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  nickname TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  pin_code TEXT,
  parent_pin_hash TEXT,
  bedtime TEXT,
  settings_initialized SMALLINT NOT NULL DEFAULT 0 CHECK (settings_initialized IN (0, 1)),
  plan_tier TEXT NOT NULL DEFAULT 'free',
  trial_started_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS parent_pin_hash TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bedtime TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS settings_initialized SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan_tier TEXT NOT NULL DEFAULT 'free';
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_started_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS child_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  avatar TEXT NOT NULL DEFAULT '🌙',
  bedtime TEXT NOT NULL DEFAULT '21:30',
  weekend_bedtime TEXT NOT NULL DEFAULT '21:30',
  is_default SMALLINT NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  archived_at TIMESTAMPTZ,
  reminder_enabled SMALLINT NOT NULL DEFAULT 0 CHECK (reminder_enabled IN (0, 1)),
  reminder_time TEXT NOT NULL DEFAULT '19:00',
  weekend_reminder_time TEXT NOT NULL DEFAULT '19:00',
  pause_reminder_minutes INTEGER NOT NULL DEFAULT 30,
  weekly_goal INTEGER NOT NULL DEFAULT 5,
  reward_text TEXT NOT NULL DEFAULT '周末一起选一个亲子活动',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE child_profiles ADD COLUMN IF NOT EXISTS weekend_bedtime TEXT NOT NULL DEFAULT '21:30';
ALTER TABLE child_profiles ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
ALTER TABLE child_profiles ADD COLUMN IF NOT EXISTS reminder_enabled SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE child_profiles ADD COLUMN IF NOT EXISTS reminder_time TEXT NOT NULL DEFAULT '19:00';
ALTER TABLE child_profiles ADD COLUMN IF NOT EXISTS weekend_reminder_time TEXT NOT NULL DEFAULT '19:00';
ALTER TABLE child_profiles ADD COLUMN IF NOT EXISTS pause_reminder_minutes INTEGER NOT NULL DEFAULT 30;
ALTER TABLE child_profiles ADD COLUMN IF NOT EXISTS weekly_goal INTEGER NOT NULL DEFAULT 5;
ALTER TABLE child_profiles ADD COLUMN IF NOT EXISTS reward_text TEXT NOT NULL DEFAULT '周末一起选一个亲子活动';

CREATE UNIQUE INDEX IF NOT EXISTS idx_child_profiles_one_default
  ON child_profiles(user_id) WHERE is_default = 1;
CREATE INDEX IF NOT EXISTS idx_child_profiles_user ON child_profiles(user_id);

CREATE TABLE IF NOT EXISTS homework_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  child_id BIGINT NOT NULL REFERENCES child_profiles(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  homework_minutes DOUBLE PRECISION DEFAULT 0,
  total_minutes DOUBLE PRECISION DEFAULT 0,
  start_time TEXT,
  end_time TEXT,
  completed SMALLINT DEFAULT 0 CHECK (completed IN (0, 1)),
  homework_done SMALLINT DEFAULT 0 CHECK (homework_done IN (0, 1)),
  correction_done SMALLINT DEFAULT 0 CHECK (correction_done IN (0, 1)),
  attitude_good SMALLINT DEFAULT 0 CHECK (attitude_good IN (0, 1)),
  playtime_type TEXT,
  playtime_minutes DOUBLE PRECISION DEFAULT 0,
  bedtime TEXT DEFAULT '21:30',
  state TEXT DEFAULT 'idle',
  homework_seconds DOUBLE PRECISION DEFAULT 0,
  paused_seconds DOUBLE PRECISION DEFAULT 0,
  remaining_seconds DOUBLE PRECISION DEFAULT 0,
  reward_choice TEXT,
  title TEXT,
  call_it_a_day SMALLINT DEFAULT 0 CHECK (call_it_a_day IN (0, 1)),
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, child_id, date)
);

ALTER TABLE homework_sessions ADD COLUMN IF NOT EXISTS state TEXT DEFAULT 'idle';
ALTER TABLE homework_sessions ADD COLUMN IF NOT EXISTS homework_seconds DOUBLE PRECISION DEFAULT 0;
ALTER TABLE homework_sessions ADD COLUMN IF NOT EXISTS paused_seconds DOUBLE PRECISION DEFAULT 0;
ALTER TABLE homework_sessions ADD COLUMN IF NOT EXISTS remaining_seconds DOUBLE PRECISION DEFAULT 0;
ALTER TABLE homework_sessions ADD COLUMN IF NOT EXISTS reward_choice TEXT;
ALTER TABLE homework_sessions ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE homework_sessions ADD COLUMN IF NOT EXISTS call_it_a_day SMALLINT DEFAULT 0;
ALTER TABLE homework_sessions ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS idx_sessions_user_child ON homework_sessions(user_id, child_id);

CREATE TABLE IF NOT EXISTS auth_tokens (
  token_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_user ON auth_tokens(user_id);

CREATE TABLE IF NOT EXISTS parent_grants (
  token_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  scope TEXT NOT NULL CHECK (scope IN ('manage', 'approve')),
  expires_at BIGINT NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_parent_grants_user ON parent_grants(user_id);

CREATE TABLE IF NOT EXISTS family_preferences (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  allow_child_switch SMALLINT NOT NULL DEFAULT 0 CHECK (allow_child_switch IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS weekly_rewards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  child_id BIGINT NOT NULL REFERENCES child_profiles(id) ON DELETE CASCADE,
  week_start TEXT NOT NULL,
  reward_text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'redeemed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, child_id, week_start)
);
CREATE INDEX IF NOT EXISTS idx_weekly_rewards_user_id ON weekly_rewards(user_id);
CREATE INDEX IF NOT EXISTS idx_weekly_rewards_child_id ON weekly_rewards(child_id);

CREATE TABLE IF NOT EXISTS streak_protections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  child_id BIGINT NOT NULL REFERENCES child_profiles(id) ON DELETE CASCADE,
  protected_date TEXT NOT NULL,
  week_start TEXT NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, child_id, protected_date)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_streak_protections_week
  ON streak_protections(user_id, child_id, week_start);
CREATE INDEX IF NOT EXISTS idx_streak_protections_child_id ON streak_protections(child_id);

CREATE TABLE IF NOT EXISTS reminder_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  child_id BIGINT NOT NULL REFERENCES child_profiles(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  status TEXT NOT NULL,
  detail TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_reminder_events_child
  ON reminder_events(user_id, child_id, created_at);
CREATE INDEX IF NOT EXISTS idx_reminder_events_child_id ON reminder_events(child_id);

CREATE TABLE IF NOT EXISTS sync_conflicts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  child_id BIGINT NOT NULL REFERENCES child_profiles(id) ON DELETE CASCADE,
  session_id BIGINT NOT NULL REFERENCES homework_sessions(id) ON DELETE CASCADE,
  device_id TEXT,
  base_version INTEGER NOT NULL,
  server_version INTEGER NOT NULL,
  client_payload TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved_server', 'resolved_client')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_sync_conflicts_user ON sync_conflicts(user_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_sync_conflicts_child_id ON sync_conflicts(child_id);
CREATE INDEX IF NOT EXISTS idx_sync_conflicts_session_id ON sync_conflicts(session_id);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  metadata TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id, created_at);

CREATE TABLE IF NOT EXISTS product_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  plan_code TEXT,
  price_point INTEGER,
  metadata TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_product_events_user ON product_events(user_id, event_type, created_at);

INSERT INTO schema_migrations (version, name)
VALUES (6, 'm11_postgres_family_platform')
ON CONFLICT (version) DO NOTHING;
`;

async function initializePostgresSchema(database) {
  return database.withClient(async client => {
    const current = await client.query(`
      SELECT CASE WHEN to_regclass('public.schema_migrations') IS NULL THEN 0
        ELSE COALESCE((SELECT MAX(version) FROM schema_migrations), 0)
      END AS version
    `);
    if (Number(current.rows[0]?.version) >= POSTGRES_SCHEMA_VERSION) return;

    await client.query('SELECT pg_advisory_lock($1)', [8311042]);
    try {
      const lockedCurrent = await client.query(`
        SELECT CASE WHEN to_regclass('public.schema_migrations') IS NULL THEN 0
          ELSE COALESCE((SELECT MAX(version) FROM schema_migrations), 0)
        END AS version
      `);
      if (Number(lockedCurrent.rows[0]?.version) >= POSTGRES_SCHEMA_VERSION) return;
      await client.query('BEGIN');
      await client.query("SET LOCAL statement_timeout = '30s'");
      await client.query(POSTGRES_SCHEMA_SQL);
      await client.query('COMMIT');
    } catch (error) {
      await client.query('ROLLBACK');
      throw error;
    } finally {
      await client.query('SELECT pg_advisory_unlock($1)', [8311042]);
    }
  });
}

module.exports = { POSTGRES_SCHEMA_SQL, POSTGRES_SCHEMA_VERSION, initializePostgresSchema };
